### ISSUE TITLE
Deploy 4 index servers

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#162]
We need at least 4 public index servers to test android app.

* Deploy 4 indexers and assign them decent domain names. For instance, indexer1.hxr.team 
* Use docker containers from #160

**Comment by romcheck** [comment]
Here they are

```
ergvein-indexer1.hxr.team
ergvein-indexer2.hxr.team
ergvein-indexer3.hxr.team
ergvein-indexer4.hxr.team
```
