### ISSUE TITLE
Connect to BTC node from client

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#182]
Make utils to handle connection with remote BTC node:
* Open and close
* Perform handshake
* Make control API:

```
btcNode :: Event t () -> Event t OutMsg -> m (Event t InMsg)
btcNode closeE outE = .....
```

* Automatically reopen connection when it is lost

Use https://hackage.haskell.org/package/haskoin-node

**Comment by LeMarwin** [comment]
haskoin-node proved to be not a good idea
