### ISSUE TITLE
Generation of private keys in Ergo

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#3]
Investigate: 

* How mnemonic phrase for master seed is generated in Ergo. 

* Which format of private keys Ergo uses. 

* How private keys are derived from master seed. 

Reference: 
https://github.com/ergoplatform/ergo-js
https://github.com/ergoplatform/ergo-wallet

**Comment by fastpok** [comment]
Closed via https://github.com/hexresearch/ergvein/commit/2fa9a46610072347f8a7d4353106d14dd93ad088
