### ISSUE TITLE
Add checking and renewing balances from transactions

### ISSUE THREAD

**Issue by Nazgull09** [hexresearch/ergvein#406]
Add tracking transactions for balances updates and update balances page dynamicly.

**Comment by NCrashed** [comment]
Elaboration:
1. It is page for balances (first page that user see)
2. Check for updating of public storage. If there is no means to detect it, add External ref or something like this.
3. Each time the public store changes set of transactions for wallet, recalculate balance for currencies.
4. Balance for BTC defined as sum of all unspent output that in user control.

**Comment by NCrashed** [comment]
Done in master
