### ISSUE TITLE
If only single currency is enabled skip balances page

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#516]
There is no need for balances page if there is only one currency enable. Lets call it mono currency mode.

But, we need to display balance anyway. Suggestion: combine balance display with history. Balance on the top and history below.

**Comment by LeMarwin** [comment]
Maybe do it in this manner? So that the balance is always visible. Might be better for sending page
![image](https://user-images.githubusercontent.com/5647149/87047262-9096ad00-c1fa-11ea-944f-7bddb385df37.png)

**Comment by NCrashed** [comment]
I think there is no need to display Bitcoin one more time. The idea to display balance across all three tabs is great.

**Comment by Nazgull09** [comment]
Maybe call it Balance or total, and add as first row with heavier font?

**Comment by LeMarwin** [comment]
And we should also display the balance in multicurrency mode. For mono currency -- skip the balances page, for multi -- show balances page + display the balance across tabs
