### ISSUE TITLE
Unconfirmed parent display

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#541]
When receiving transaction that is based on outputs that are not in any block yet we need to mark them as more dangerous than even txs with 0 confirmations.

How it is displayed in electrum:
![Screenshot from 2020-07-15 09-58-27](https://user-images.githubusercontent.com/2116167/87514988-ce288980-c683-11ea-941e-cfc267cd56df.png)

**Comment by fastpok** [comment]
Closed in #559

**Comment by fastpok** [comment]
Unconfirmed parent indication stopped working

**Comment by fastpok** [comment]
Fixed in https://github.com/hexresearch/ergvein/pull/744
