### ISSUE TITLE
UI fixes required 

### ISSUE THREAD

**Issue by voidlizard** [hexresearch/ergvein#547]
- [ ]  More readable Balance - right now it's barely recognizable

Suggest new color/place for balance - on top or bottom of the   screen

 - [ ]  Status bar / log page

Right now it's unclear what's happening in UI in every particular moment. Sometime it looks like it UI is frozen.
Solution: introduce the status bar with the current activity / it's status. Click on status bar should lead to the status page where are all current activities are collected. It may looks as a fixed set of activities with their timestamp and status or log-style scrollable screen.

- [ ] Settings menu should be a whole screen

Currently the settings menu looks weird for mobile app. It should be a settings screen instead.

- [ ] Transaction info fix

Right now there is a low-level transaction information as a text representation of parsing of BTC blocks/transaction info. It's very confusing for the most of users.

Solution: show significant information on transaction details:
 - when
 - how much
 - confirmations number
 -  balance change ( transaction's amount, change of balance, balance after this transaction )
 - show low-level transaction information on a separate screen

- [ ]  Show estimated time for transaction to confirm

- [ ]  Provide indexers automatically
There is no point for most users to input the indexers manually. We have to provide and choose them automatically,
giving the ability to inactivate some of them if they are not accessible or being an obstacle. Just add checkbox for each indexer
and let user uncheck it if they want.

- [ ] Reduce haskellism in UI.

Height is ```Just XXXXXXX``` - wut?

**Comment by NCrashed** [comment]
Fixed
