### ISSUE TITLE
Rework Transaction Info page

### ISSUE THREAD

**Issue by Nazgull09** [hexresearch/ergvein#548]
Move low-level information down, add link to id, add link to block. 
For refill transactions:

> Id (hash with link to block explorer)
> Amount (wallet's balance Delta) 
> Balance before -> balance after
> Time when we saw the tx for the first time (either mempool include time or block time)
> Confirmations (0 is unconfirmed and mark unconfirmed parent if one of the inputs is not confirmed)
> Block (link to blockexplorer)
> Outputs (mark which one our outputs)
> Raw transaction
Remove Fee and Inputs fields.

For withdrawals:
> Id (hash with link to block explorer)
> Amount (wallet's balance Delta) 
> Fee (total and satoshi per byte)
> Balance before -> balance after
> Time when we posted transaction into blockchain
> Confirmations (0 is unconfirmed and mark unconfirmed parent if one of the inputs is not confirmed)
> Block (link to blockexplorer)
> Inputs (only our inputs)
> Outputs (mark which one our outputs (for change))
> Raw transaction

**Comment by NCrashed** [comment]
Implemented
