### ISSUE TITLE
Add roadmap to the website

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#673]
Add work flow that contains sequence of tasks that are planned.

Current roadmap:
1. Polishing BTC wallet.
1. Ergo wallet (some work is already done)
1. USDT Omni wallet.
1. Manual BTC-USDT, BTC-Ergo, Ergo-USDT atomic swaps.
1. Implementing Cypra token and wallet for it.
1. Atomic swaps bulletin service.

**Comment by LeMarwin** [comment]
Outdated
