### ISSUE TITLE
Scanner didn't confirm transaction

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#712]
Problematic TX: https://live.blockcypher.com/btc/tx/e2b3a88d8ef0aa39289b038ffdb2a9df2af75e63f2788bb14c41793dbb81644a/

1. Check that indexers have blocks for the tx.
2. Check operation of scanner for new blocks.

**Comment by fastpok** [comment]
Investigation has shown that the problem is in obtaining filters.
When wallet tries to get fresh filters from indexer, connection hangs.

Indexer throws the following error message:
`ergvein-index-server: writev: resource vanished (Broken pipe)`

**Comment by fastpok** [comment]
It looks like the problem is closely related to getting heights from bitcoin nodes

**Comment by fastpok** [comment]
The main problem, most likely, is the incorrect deserialization of the `MFiltersEvent` messages.

**Comment by fastpok** [comment]
Closing this for now.

**Comment by fastpok** [comment]
The problem was caused by the `getOpenSyncedConns` function not working properly. The height on the side of the wallet was miscalculated.
