### ISSUE TITLE
Headers storage

### ISSUE THREAD

**Issue by LeMarwin** [hexresearch/ergvein#732]
Reasoning:

Right now we calculate heights by trying to catch up with the tip via ``getheaders`` requests from hard-coded checkpoints. This method is not fork-safe. We probably have a bug because of that, when the height catch up halts at lower height.

Making it fork-safe requires the wallet to be able to backtrack the chain. For this reason we need to be able to store all headers.

What to do:
* Pull apart haskoin-core and separate headers storage into a separate library
* Use that storage to store headers, starting from the last hard-coded checkpoint
* Use the storage to calculate heights

**Comment by NCrashed** [comment]
Delay that change

**Comment by NCrashed** [comment]
Implmented in #921
