### ISSUE TITLE
Gracefully close database in indexers

### ISSUE THREAD

**Issue by Shimuuar** [hexresearch/ergvein#796]
Currently level DB databases are never closed and we just rely on their robustness to crashes. However doing so reliably is not easy.  Any attempt to use database handle after close will lead to memory corruption and possible crash & data corruption. `withDatabase` is not safe either since child thread may outlive bracket. 

Sqlite has same problem and in hschain it was solved by storing it in MVar: `MVar (Maybe Connection)`. Once connection is close `Nothing` is put into MVar and it's not possible to query database anymore. As side effect all DB access is serialised but it wasn't serious problem there

**Comment by NCrashed** [comment]
Closed by #819
