### ISSUE TITLE
Mempool tree research

### ISSUE THREAD

**Issue by LeMarwin** [hexresearch/ergvein#964]
Discover optimal parameters for prefix tree (prefix length) and M and P parameters for mempool filters.

Do this with a rust tool in a way that it can be transformed into a separate library for mempool filter tree management 

A part of #963

**Comment by LeMarwin** [comment]
Made a test tool. It pulls a number of blocks, gets all transactions and sorts them into buckets, based on first 10 bits of transaction's hash.
Afterwards the tool constructs Golomb-Rice filters for each bucket and a full filter for all transactions together.

I decided to skip adding TxIn's to the filter to simplify development. 
On average transactions have the same number of inputs and outputs. 
[Inputs/tx](https://bitcoinvisuals.com/chain-input-count-tx)
[Outputs/tx](https://bitcoinvisuals.com/chain-output-count-tx)
Based on that, you can mentally divide # of transactions by two to get the simulated mempool size.


\# blocks | # transactions | Full filter, kb | Avg bucket filter, kb |   Bundle,kb  |
---------|----------------|-------------|-------------------|-----------|
   50    |    82016       |   141.42    |  0.18 ± 0.06      |   179.35  |
   100   |    164599      |   295.54    |  0.36 ± 0.13      |   363.83  |
   200   |    368902      |   634.43    |  0.77 ± 0.17      |   786.94  |
-------------------------------------------------------------------------

**Comment by NCrashed** [comment]
Done
